#############################################################################
# Makefile for building: path_finding_better
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  path_finding_better.pro
# Template: app
# Command: /Users/gabeorlanski/Qt/5.2.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile path_finding_better.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../../Qt/5.2.1/clang_64/mkspecs/macx-clang -I. -I/usr/local/include
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -L/usr/local/lib -lsfml-graphics -lsfml-system -lsfml-network -lsfml-window 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/gabeorlanski/Qt/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		node.cpp \
		Animation.cpp \
		AnimatedSprite.cpp 
OBJECTS       = main.o \
		node.o \
		Animation.o \
		AnimatedSprite.o
DIST          = ../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		path_finding_better.pro \
		path_finding_better.pro
QMAKE_TARGET  = path_finding_better
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = path_finding_better

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: path_finding_better.pro ../../../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf \
		path_finding_better.pro
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile path_finding_better.pro
../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/c++11.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/declarative_debug.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.2.1/clang_64/mkspecs/features/lex.prf:
path_finding_better.pro:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile path_finding_better.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/path_finding_better1.0.0 || mkdir -p .tmp/path_finding_better1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/path_finding_better1.0.0/ && (cd `dirname .tmp/path_finding_better1.0.0` && $(TAR) path_finding_better1.0.0.tar path_finding_better1.0.0 && $(COMPRESS) path_finding_better1.0.0.tar) && $(MOVE) `dirname .tmp/path_finding_better1.0.0`/path_finding_better1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/path_finding_better1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp /usr/local/include/SFML/Graphics.hpp \
		/usr/local/include/SFML/Window.hpp \
		/usr/local/include/SFML/System.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/System/Clock.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/System/Err.hpp \
		/usr/local/include/SFML/System/InputStream.hpp \
		/usr/local/include/SFML/System/Lock.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Mutex.hpp \
		/usr/local/include/SFML/System/Sleep.hpp \
		/usr/local/include/SFML/System/String.hpp \
		/usr/local/include/SFML/System/Thread.hpp \
		/usr/local/include/SFML/System/Thread.inl \
		/usr/local/include/SFML/System/ThreadLocal.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.hpp \
		/usr/local/include/SFML/System/ThreadLocalPtr.inl \
		/usr/local/include/SFML/System/Utf.hpp \
		/usr/local/include/SFML/System/Utf.inl \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/System/Vector3.hpp \
		/usr/local/include/SFML/System/Vector3.inl \
		/usr/local/include/SFML/Window/Context.hpp \
		/usr/local/include/SFML/Window/Export.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/ContextSettings.hpp \
		/usr/local/include/SFML/Window/Event.hpp \
		/usr/local/include/SFML/Window/Joystick.hpp \
		/usr/local/include/SFML/Window/Keyboard.hpp \
		/usr/local/include/SFML/Window/Mouse.hpp \
		/usr/local/include/SFML/Window/VideoMode.hpp \
		/usr/local/include/SFML/Window/Window.hpp \
		/usr/local/include/SFML/Window/WindowHandle.hpp \
		/usr/local/include/SFML/Window/WindowStyle.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Graphics/Font.hpp \
		/usr/local/include/SFML/Graphics/Glyph.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/RenderTexture.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/Graphics/RenderWindow.hpp \
		/usr/local/include/SFML/Graphics/Shader.hpp \
		/usr/local/include/SFML/Graphics/Shape.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		/usr/local/include/SFML/Graphics/VertexArray.hpp \
		/usr/local/include/SFML/Graphics/CircleShape.hpp \
		/usr/local/include/SFML/Graphics/RectangleShape.hpp \
		/usr/local/include/SFML/Graphics/ConvexShape.hpp \
		/usr/local/include/SFML/Graphics/Sprite.hpp \
		/usr/local/include/SFML/Graphics/Text.hpp \
		Animation.hpp \
		AnimatedSprite.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

node.o: node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

Animation.o: Animation.cpp Animation.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/Export.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Animation.o Animation.cpp

AnimatedSprite.o: AnimatedSprite.cpp AnimatedSprite.hpp \
		/usr/local/include/SFML/Graphics/RenderTarget.hpp \
		/usr/local/include/SFML/Graphics/Export.hpp \
		/usr/local/include/SFML/Config.hpp \
		/usr/local/include/SFML/Graphics/Color.hpp \
		/usr/local/include/SFML/Graphics/Rect.hpp \
		/usr/local/include/SFML/System/Vector2.hpp \
		/usr/local/include/SFML/System/Vector2.inl \
		/usr/local/include/SFML/Graphics/Rect.inl \
		/usr/local/include/SFML/Graphics/View.hpp \
		/usr/local/include/SFML/Graphics/Transform.hpp \
		/usr/local/include/SFML/Graphics/BlendMode.hpp \
		/usr/local/include/SFML/Graphics/RenderStates.hpp \
		/usr/local/include/SFML/Graphics/PrimitiveType.hpp \
		/usr/local/include/SFML/Graphics/Vertex.hpp \
		/usr/local/include/SFML/System/NonCopyable.hpp \
		/usr/local/include/SFML/System/Export.hpp \
		/usr/local/include/SFML/System/Time.hpp \
		/usr/local/include/SFML/Graphics/Drawable.hpp \
		/usr/local/include/SFML/Graphics/Transformable.hpp \
		Animation.hpp \
		/usr/local/include/SFML/Graphics/Texture.hpp \
		/usr/local/include/SFML/Graphics/Image.hpp \
		/usr/local/include/SFML/Window/GlResource.hpp \
		/usr/local/include/SFML/Window/Export.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AnimatedSprite.o AnimatedSprite.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

